# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# MINIO_IMAGE_NAME                - This optional environment variable is used to determine the docker image name used to run Minio.
#                                   Default: bitnami/minio:2024 [https://hub.docker.com/r/bitnami/minio]
# MINIO_API_PORT                  - This environment variable is used to determine the port to expose the Minio API.
#                                   Default: 9000
# MINIO_CONSOLE_PORT              - This environment variable is used to determine the port to expose the Minio console.
#                                   Default: 9001
# MINIO_DEFAULT_BUCKETS           - This environment variable is used to determine the default bucket names.
#                                   Default: null [example: 'bucket_01,bucket_02']
# MINIO_ROOT_USER                 - This environment variable sets the root user for Minio.
#
# MINIO_ROOT_PASSWORD             - This environment variable sets the root password for Minio.
#
# PROJ_DIR                        - This is to specify where your project directory is or where you need your volume data stored
#                                 - Default: $PWD
#
#
# Feel free to modify this file to suit your needs.


x-volume-common:
  &volume-common
  driver: local
  driver_opts:
    &volume-driver-opts-common
    type: none
    o: bind

services:
  minio:
    image: ${MINIO_IMAGE_NAME:-bitnami/minio:2024}
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-null}
    volumes:
      - minio-volume:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "mc", "-ready", "local"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 20s
    restart: on-failure:3
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    

volumes:
  minio-volume:
    <<: *volume-common
    driver_opts:
      <<: *volume-driver-opts-common
      device: ${PROJ_DIR:-.}/minio-data