# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# REDIS_IMAGE_NAME                - This optional environment variable is used to determine the docker image name used to run Redis.
#                                   Default: bitnami/redis:7.4 [https://hub.docker.com/r/bitnami/redis]
# REDIS_PORT                      - This environment variable is used to determine the port to expose the service.
#                                 - Default: 6379
# REDIS_PASSWORD                  - This environment variable sets the master password for Redis.
#
#
# PROJ_DIR                        - This is to specify where your project directory is or where you need your volume data stored
#                                 - Default: $PWD
#
#
# Feel free to modify this file to suit your needs.


x-volume-common:
  &volume-common
  driver: local
  driver_opts:
    &volume-driver-opts-common
    type: none
    o: bind

services:
  redis:
    image: ${REDIS_IMAGE_NAME:-bitnami/redis:7.4}
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?error}
    volumes:
      - redis-volume:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "--raw", "incr", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: on-failure:3
    ports:
      - "${REDIS_PORT:-6379}:6379"
    

volumes:
  redis-volume:
    <<: *volume-common
    driver_opts:
      <<: *volume-driver-opts-common
      device: ${PROJ_DIR:-.}/redis-data